version: '3'
services:
  db:
    image: postgres:10.4
    environment:
      POSTGRES_USER: myapp
    ports:
      - 5432:5432
    volumes:
      - ./pg-data:/var/lib/postgresql/data
  web:
    build:
      context: ./web
    environment:
      RAILS_ENV: development
    volumes:
      - ./web:/myapp
      - ./bundle:/usr/local/bundle
    ports:
      - 3000:3000
    command: rails s -p 3000 -b '0.0.0.0'
    links:
      - db
